site_name: Wiki
site_url: https://www.curren-dynamics.com
site_author: Hayden Curren
repo_url: https://github.com/orgs/Curren-Dynamics/repositories
repo_name: Curren Dynamics on GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logos/logo.png
  favicon: assets/logos/logo_only.png
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Projects: 
    - Overview: projects.md
    - ESCuino X2:
      - Overview: ESCuino_X2.md
      - Development: development.md
      - Hardware: hardware.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.inlinehilite

plugins:
  - search

extra_css:
  - styles/extra.css
